// Comprehensive mock stock data for LimeoXNG screener

// Generate historical price data for charts
const generateChartData = (basePrice: number, days: number = 60) => {
  const data: any[] = [];
  let price = basePrice;
  const today = new Date();
  
  for (let i = days; i >= 0; i--) {
    const date = new Date(today);
    date.setDate(date.getDate() - i);
    
    // Random walk with slight upward bias
    const change = (Math.random() - 0.48) * (basePrice * 0.03);
    price = Math.max(price + change, basePrice * 0.5);
    
    data.push({
      date: date.toISOString().split('T')[0],
      price: parseFloat(price.toFixed(2)),
      volume: Math.floor(Math.random() * 50000000 + 1000000)
    });
  }
  
  return data;
};

// Mock news data
export const mockNews = [
  {
    id: 1,
    date: '2025-01-20',
    time: '09:30 AM',
    source: 'Reuters',
    headline: 'Apple Reports Record Q4 Earnings, Beats Expectations',
    sentiment: 'positive',
    tickers: ['AAPL']
  },
  {
    id: 2,
    date: '2025-01-20',
    time: '08:15 AM',
    source: 'Bloomberg',
    headline: 'Tesla Unveils New Model Line for 2025',
    sentiment: 'positive',
    tickers: ['TSLA']
  },
  {
    id: 3,
    date: '2025-01-20',
    time: '07:45 AM',
    source: 'CNBC',
    headline: 'Microsoft Azure Revenue Growth Slows in Q4',
    sentiment: 'neutral',
    tickers: ['MSFT']
  },
  {
    id: 4,
    date: '2025-01-19',
    time: '04:30 PM',
    source: 'Wall Street Journal',
    headline: 'Amazon Expands Same-Day Delivery to 50 New Cities',
    sentiment: 'positive',
    tickers: ['AMZN']
  },
  {
    id: 5,
    date: '2025-01-19',
    time: '03:20 PM',
    source: 'MarketWatch',
    headline: 'NVIDIA CEO Discusses AI Chip Supply Constraints',
    sentiment: 'neutral',
    tickers: ['NVDA']
  },
  {
    id: 6,
    date: '2025-01-19',
    time: '02:15 PM',
    source: 'Financial Times',
    headline: 'JPMorgan Raises Interest Rate Forecast',
    sentiment: 'neutral',
    tickers: ['JPM']
  },
  {
    id: 7,
    date: '2025-01-19',
    time: '01:05 PM',
    source: 'Reuters',
    headline: 'Meta Platforms Faces Regulatory Scrutiny in EU',
    sentiment: 'negative',
    tickers: ['META']
  },
  {
    id: 8,
    date: '2025-01-19',
    time: '11:30 AM',
    source: 'Bloomberg',
    headline: 'Google Announces New AI Search Features',
    sentiment: 'positive',
    tickers: ['GOOGL']
  }
];

export const mockStocks: any[] = [
  {
    no: 1,
    ticker: 'A',
    company: 'Agilent Technologies Inc',
    sector: 'Healthcare',
    industry: 'Diagnostics & Research',
    country: 'USA',
    marketCap: '40.94B',
    pe: 33.86,
    forwardPe: 29.12,
    peg: 2.45,
    ps: 4.23,
    pb: 5.67,
    pc: 18.92,
    pfcf: 24.56,
    dividendYield: '0.74%',
    payoutRatio: '24.5%',
    eps: 4.26,
    price: 144.40,
    change: '0.39%',
    volume: 1843608,
    avgVolume: '1.87M',
    relVolume: 0.99,
    perf1w: '2.35%',
    perf1m: '5.67%',
    perf3m: '8.92%',
    perf6m: '12.45%',
    perfYtd: '15.23%',
    perf1y: '22.34%',
    beta: 1.12,
    atr: 3.45,
    volatility: '1.89% 2.34%',
    rsi: 58.32,
    recom: 2.3,
    targetPrice: 156.00,
    insiderOwn: '0.10%',
    insiderTrans: '-5.23%',
    instOwn: '89.34%',
    instTrans: '2.45%',
    roa: '8.92%',
    roe: '18.45%',
    roi: '12.34%',
    currRatio: 2.34,
    quickRatio: 1.89,
    ltDebtEq: 0.45,
    debtEq: 0.52,
    grossMargin: '52.34%',
    operMargin: '21.45%',
    profitMargin: '16.78%',
    earningsDate: 'Feb 14 BMO',
    shortFloat: '1.23%',
    shortRatio: 2.34,
    optionable: 'Yes',
    shortable: 'Yes',
    chartData: generateChartData(144.40)
  },
  {
    no: 2,
    ticker: 'AA',
    company: 'Alcoa Corp',
    sector: 'Basic Materials',
    industry: 'Aluminum',
    country: 'USA',
    marketCap: '9.51B',
    pe: 8.34,
    forwardPe: 12.45,
    peg: 0.87,
    ps: 0.45,
    pb: 1.23,
    pc: 8.92,
    pfcf: 11.34,
    dividendYield: '1.09%',
    payoutRatio: '9.1%',
    eps: 4.40,
    price: 36.72,
    change: '0.47%',
    volume: 4072018,
    avgVolume: '4.23M',
    relVolume: 0.96,
    perf1w: '-1.23%',
    perf1m: '3.45%',
    perf3m: '-2.34%',
    perf6m: '8.92%',
    perfYtd: '12.45%',
    perf1y: '18.23%',
    beta: 1.89,
    atr: 1.92,
    volatility: '2.34% 3.12%',
    rsi: 52.18,
    recom: 2.8,
    targetPrice: 42.00,
    insiderOwn: '0.23%',
    insiderTrans: '1.23%',
    instOwn: '92.45%',
    instTrans: '0.89%',
    roa: '3.45%',
    roe: '9.23%',
    roi: '5.67%',
    currRatio: 1.78,
    quickRatio: 0.92,
    ltDebtEq: 0.67,
    debtEq: 0.78,
    grossMargin: '18.92%',
    operMargin: '8.45%',
    profitMargin: '4.23%',
    earningsDate: 'Jan 17 AMC',
    shortFloat: '3.45%',
    shortRatio: 1.89,
    optionable: 'Yes',
    shortable: 'Yes',
    chartData: generateChartData(36.72)
  },
  {
    no: 3,
    ticker: 'AAL',
    company: 'American Airlines Group Inc',
    sector: 'Industrials',
    industry: 'Airlines',
    country: 'USA',
    marketCap: '8.14B',
    pe: 14.82,
    forwardPe: 8.92,
    peg: 1.23,
    ps: 0.23,
    pb: 2.45,
    pc: 5.67,
    pfcf: 8.23,
    dividendYield: '-',
    payoutRatio: '-',
    eps: 0.83,
    price: 12.33,
    change: '-0.24%',
    volume: 53618432,
    avgVolume: '42.3M',
    relVolume: 1.27,
    perf1w: '3.45%',
    perf1m: '8.92%',
    perf3m: '15.67%',
    perf6m: '22.34%',
    perfYtd: '18.92%',
    perf1y: '34.56%',
    beta: 1.56,
    atr: 0.78,
    volatility: '3.45% 4.23%',
    rsi: 64.23,
    recom: 3.2,
    targetPrice: 16.50,
    insiderOwn: '0.45%',
    insiderTrans: '-2.34%',
    instOwn: '78.92%',
    instTrans: '3.45%',
    roa: '1.23%',
    roe: '18.92%',
    roi: '3.45%',
    currRatio: 0.89,
    quickRatio: 0.67,
    ltDebtEq: 4.56,
    debtEq: 5.23,
    grossMargin: '28.92%',
    operMargin: '5.67%',
    profitMargin: '1.23%',
    earningsDate: 'Jan 24 BMO',
    shortFloat: '5.67%',
    shortRatio: 3.45,
    optionable: 'Yes',
    shortable: 'Yes',
    chartData: generateChartData(12.33)
  },
  {
    no: 4,
    ticker: 'AAPL',
    company: 'Apple Inc',
    sector: 'Technology',
    industry: 'Consumer Electronics',
    country: 'USA',
    marketCap: '3968.34B',
    pe: 36.00,
    forwardPe: 31.45,
    peg: 3.12,
    ps: 9.23,
    pb: 52.34,
    pc: 28.92,
    pfcf: 34.56,
    dividendYield: '0.42%',
    payoutRatio: '15.2%',
    eps: 7.46,
    price: 268.56,
    change: '0.42%',
    volume: 39302025,
    avgVolume: '45.2M',
    relVolume: 0.87,
    perf1w: '1.23%',
    perf1m: '4.56%',
    perf3m: '12.34%',
    perf6m: '18.92%',
    perfYtd: '22.45%',
    perf1y: '38.67%',
    beta: 1.21,
    atr: 4.23,
    volatility: '1.56% 2.12%',
    rsi: 61.45,
    recom: 1.8,
    targetPrice: 295.00,
    insiderOwn: '0.07%',
    insiderTrans: '-1.23%',
    instOwn: '61.34%',
    instTrans: '1.89%',
    roa: '28.92%',
    roe: '148.23%',
    roi: '45.67%',
    currRatio: 0.98,
    quickRatio: 0.87,
    ltDebtEq: 1.78,
    debtEq: 1.92,
    grossMargin: '46.23%',
    operMargin: '32.45%',
    profitMargin: '26.34%',
    earningsDate: 'Jan 30 AMC',
    shortFloat: '0.89%',
    shortRatio: 1.23,
    optionable: 'Yes',
    shortable: 'Yes',
    chartData: generateChartData(268.56)
  },
  {
    no: 5,
    ticker: 'ABBV',
    company: 'AbbVie Inc',
    sector: 'Healthcare',
    industry: 'Drug Manufacturers - General',
    country: 'USA',
    marketCap: '322.45B',
    pe: 42.34,
    forwardPe: 15.67,
    peg: 2.89,
    ps: 5.78,
    pb: 49.23,
    pc: 22.45,
    pfcf: 28.92,
    dividendYield: '3.21%',
    payoutRatio: '135.6%',
    eps: 4.29,
    price: 181.45,
    change: '1.23%',
    volume: 5234567,
    avgVolume: '6.78M',
    relVolume: 0.77,
    perf1w: '2.34%',
    perf1m: '6.78%',
    perf3m: '11.23%',
    perf6m: '15.67%',
    perfYtd: '19.45%',
    perf1y: '28.92%',
    beta: 0.67,
    atr: 2.89,
    volatility: '1.23% 1.78%',
    rsi: 55.67,
    recom: 2.1,
    targetPrice: 195.00,
    insiderOwn: '0.05%',
    insiderTrans: '0.34%',
    instOwn: '71.23%',
    instTrans: '2.34%',
    roa: '8.45%',
    roe: '91.23%',
    roi: '15.67%',
    currRatio: 0.89,
    quickRatio: 0.67,
    ltDebtEq: 5.67,
    debtEq: 6.23,
    grossMargin: '72.34%',
    operMargin: '31.45%',
    profitMargin: '10.12%',
    earningsDate: 'Feb 7 BMO',
    shortFloat: '1.45%',
    shortRatio: 2.12,
    optionable: 'Yes',
    shortable: 'Yes',
    chartData: generateChartData(181.45)
  }
];

// Generate more mock stocks (total 100 for pagination testing)
const additionalTickers = [
  { ticker: 'MSFT', company: 'Microsoft Corporation', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'GOOGL', company: 'Alphabet Inc Class A', sector: 'Communication Services', industry: 'Internet Content & Information' },
  { ticker: 'AMZN', company: 'Amazon.com Inc', sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  { ticker: 'TSLA', company: 'Tesla Inc', sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  { ticker: 'META', company: 'Meta Platforms Inc', sector: 'Communication Services', industry: 'Internet Content & Information' },
  { ticker: 'NVDA', company: 'NVIDIA Corporation', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'JPM', company: 'JPMorgan Chase & Co', sector: 'Financial', industry: 'Banks - Diversified' },
  { ticker: 'V', company: 'Visa Inc', sector: 'Financial', industry: 'Credit Services' },
  { ticker: 'WMT', company: 'Walmart Inc', sector: 'Consumer Defensive', industry: 'Discount Stores' },
  { ticker: 'JNJ', company: 'Johnson & Johnson', sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  { ticker: 'PG', company: 'Procter & Gamble Co', sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  { ticker: 'MA', company: 'Mastercard Inc', sector: 'Financial', industry: 'Credit Services' },
  { ticker: 'HD', company: 'Home Depot Inc', sector: 'Consumer Cyclical', industry: 'Home Improvement Retail' },
  { ticker: 'BAC', company: 'Bank of America Corp', sector: 'Financial', industry: 'Banks - Diversified' },
  { ticker: 'XOM', company: 'Exxon Mobil Corporation', sector: 'Energy', industry: 'Oil & Gas Integrated' },
  { ticker: 'CVX', company: 'Chevron Corporation', sector: 'Energy', industry: 'Oil & Gas Integrated' },
  { ticker: 'KO', company: 'Coca-Cola Co', sector: 'Consumer Defensive', industry: 'Beverages - Non-Alcoholic' },
  { ticker: 'PEP', company: 'PepsiCo Inc', sector: 'Consumer Defensive', industry: 'Beverages - Non-Alcoholic' },
  { ticker: 'COST', company: 'Costco Wholesale Corporation', sector: 'Consumer Defensive', industry: 'Discount Stores' },
  { ticker: 'NFLX', company: 'Netflix Inc', sector: 'Communication Services', industry: 'Entertainment' }
];

for (let i = 0; i < additionalTickers.length; i++) {
  const item = additionalTickers[i];
  const randomPrice = parseFloat((Math.random() * 500 + 10).toFixed(2));
  const randomChange = (Math.random() * 10 - 5).toFixed(2);
  const randomVolume = Math.floor(Math.random() * 50000000 + 1000000);
  const randomPE = parseFloat((Math.random() * 50 + 5).toFixed(2));
  const randomMarketCap = (Math.random() * 3000 + 10).toFixed(2) + 'B';
  
  mockStocks.push({
    no: mockStocks.length + 1,
    ticker: item.ticker,
    company: item.company,
    sector: item.sector,
    industry: item.industry,
    country: 'USA',
    marketCap: randomMarketCap,
    pe: randomPE,
    forwardPe: parseFloat((randomPE * 0.9).toFixed(2)),
    peg: parseFloat((Math.random() * 3 + 0.5).toFixed(2)),
    ps: parseFloat((Math.random() * 10 + 0.5).toFixed(2)),
    pb: parseFloat((Math.random() * 50 + 1).toFixed(2)),
    pc: parseFloat((Math.random() * 30 + 5).toFixed(2)),
    pfcf: parseFloat((Math.random() * 40 + 5).toFixed(2)),
    dividendYield: Math.random() > 0.5 ? (Math.random() * 5).toFixed(2) + '%' : '-',
    payoutRatio: Math.random() > 0.5 ? (Math.random() * 100).toFixed(1) + '%' : '-',
    eps: parseFloat((Math.random() * 20 + 0.5).toFixed(2)),
    price: randomPrice,
    change: randomChange + '%',
    volume: randomVolume,
    avgVolume: (randomVolume * 1.2 / 1000000).toFixed(2) + 'M',
    relVolume: parseFloat((Math.random() * 2 + 0.5).toFixed(2)),
    perf1w: (Math.random() * 10 - 5).toFixed(2) + '%',
    perf1m: (Math.random() * 15 - 7.5).toFixed(2) + '%',
    perf3m: (Math.random() * 25 - 12.5).toFixed(2) + '%',
    perf6m: (Math.random() * 40 - 20).toFixed(2) + '%',
    perfYtd: (Math.random() * 30 - 15).toFixed(2) + '%',
    perf1y: (Math.random() * 50 - 25).toFixed(2) + '%',
    beta: parseFloat((Math.random() * 2 + 0.5).toFixed(2)),
    atr: parseFloat((Math.random() * 5 + 1).toFixed(2)),
    volatility: (Math.random() * 3 + 1).toFixed(2) + '% ' + (Math.random() * 4 + 1.5).toFixed(2) + '%',
    rsi: parseFloat((Math.random() * 80 + 20).toFixed(2)),
    recom: parseFloat((Math.random() * 4 + 1).toFixed(1)),
    targetPrice: parseFloat((randomPrice * (1 + Math.random() * 0.3)).toFixed(2)),
    insiderOwn: (Math.random() * 10).toFixed(2) + '%',
    insiderTrans: (Math.random() * 10 - 5).toFixed(2) + '%',
    instOwn: (Math.random() * 80 + 10).toFixed(2) + '%',
    instTrans: (Math.random() * 5 - 2.5).toFixed(2) + '%',
    roa: (Math.random() * 30).toFixed(2) + '%',
    roe: (Math.random() * 150).toFixed(2) + '%',
    roi: (Math.random() * 50).toFixed(2) + '%',
    currRatio: parseFloat((Math.random() * 3 + 0.5).toFixed(2)),
    quickRatio: parseFloat((Math.random() * 2 + 0.3).toFixed(2)),
    ltDebtEq: parseFloat((Math.random() * 6).toFixed(2)),
    debtEq: parseFloat((Math.random() * 7).toFixed(2)),
    grossMargin: (Math.random() * 70 + 10).toFixed(2) + '%',
    operMargin: (Math.random() * 40 + 5).toFixed(2) + '%',
    profitMargin: (Math.random() * 30 + 2).toFixed(2) + '%',
    earningsDate: 'Feb ' + Math.floor(Math.random() * 28 + 1) + ' AMC',
    shortFloat: (Math.random() * 15).toFixed(2) + '%',
    shortRatio: parseFloat((Math.random() * 5 + 0.5).toFixed(2)),
    optionable: 'Yes',
    shortable: 'Yes',
    chartData: generateChartData(randomPrice)
  });
}

export const filterOptions = {
  exchange: ['Any', 'AMEX', 'CBOE', 'NASDAQ', 'NYSE'],
  index: ['Any', 'S&P 500', 'NASDAQ 100', 'DJIA', 'RUSSELL 2000'],
  sector: ['Any', 'Basic Materials', 'Communication Services', 'Consumer Cyclical', 'Consumer Defensive', 'Energy', 'Financial', 'Healthcare', 'Industrials', 'Real Estate', 'Technology', 'Utilities'],
  industry: ['Any', 'Stocks only (ex-Funds)', 'Advertising Agencies', 'Aerospace & Defense', 'Airlines', 'Aluminum', 'Auto Manufacturers', 'Banks - Diversified', 'Biotechnology', 'Consumer Electronics', 'Credit Services', 'Diagnostics & Research', 'Discount Stores', 'Drug Manufacturers - General', 'Entertainment', 'Home Improvement Retail', 'Internet Content & Information', 'Internet Retail', 'Oil & Gas Integrated', 'Semiconductors', 'Software - Infrastructure'],
  country: ['Any', 'USA', 'Foreign (ex-USA)', 'China', 'Canada', 'United Kingdom', 'Germany', 'Japan'],
  marketCap: ['Any', 'Mega ($200bln and more)', 'Large ($10bln to $200bln)', 'Mid ($2bln to $10bln)', 'Small ($300mln to $2bln)', 'Micro ($50mln to $300mln)', 'Nano (under $50mln)', '+Large (over $10bln)', '+Mid (over $2bln)', '+Small (over $300mln)', '+Micro (over $50mln)', '-Large (under $200bln)', '-Mid (under $10bln)', '-Small (under $2bln)', '-Micro (under $300mln)'],
  dividendYield: ['Any', 'None (0%)', 'Positive (>0%)', 'High (>5%)', 'Very High (>10%)', 'Over 1%', 'Over 2%', 'Over 3%', 'Over 4%', 'Over 5%'],
  shortFloat: ['Any', 'Low (<5%)', 'High (>20%)', 'Under 5%', 'Under 10%', 'Under 15%', 'Over 5%', 'Over 10%', 'Over 15%', 'Over 20%'],
  analystRecom: ['Any', 'Strong Buy (1)', 'Buy or better', 'Buy', 'Hold or better', 'Hold', 'Hold or worse', 'Sell', 'Sell or worse', 'Strong Sell (5)'],
  optionShort: ['Any', 'Optionable', 'Shortable', 'Optionable and shortable', 'Not optionable', 'Not shortable'],
  earningsDate: ['Any', 'Today', 'Today Before Market Open', 'Today After Market Close', 'Tomorrow', 'Next 5 Days', 'This Week', 'Next Week', 'This Month'],
  averageVolume: ['Any', 'Under 50K', 'Under 100K', 'Under 500K', 'Under 1M', 'Over 50K', 'Over 100K', 'Over 500K', 'Over 1M', 'Over 2M'],
  relativeVolume: ['Any', 'Over 10', 'Over 5', 'Over 3', 'Over 2', 'Over 1.5', 'Over 1', 'Over 0.5', 'Under 2', 'Under 1', 'Under 0.5'],
  currentVolume: ['Any', 'Under 50K', 'Under 100K', 'Under 500K', 'Under 1M', 'Over 50K', 'Over 100K', 'Over 500K', 'Over 1M', 'Over 2M', 'Over 5M', 'Over 10M'],
  price: ['Any', 'Under $1', 'Under $5', 'Under $10', 'Under $20', 'Under $50', 'Over $1', 'Over $5', 'Over $10', 'Over $20', 'Over $50', 'Over $100', '$1 to $5', '$5 to $10', '$10 to $20', '$20 to $50', '$50 to $100'],
  targetPrice: ['Any', '50% Above Price', '40% Above Price', '30% Above Price', '20% Above Price', '10% Above Price', 'Above Price', 'Below Price', '10% Below Price', '20% Below Price'],
  ipoDate: ['Any', 'Today', 'In the last week', 'In the last month', 'In the last year', 'More than a year ago', 'More than 5 years ago', 'More than 10 years ago'],
  sharesOutstanding: ['Any', 'Under 1M', 'Under 5M', 'Under 10M', 'Under 50M', 'Under 100M', 'Over 1M', 'Over 5M', 'Over 10M', 'Over 50M', 'Over 100M'],
  float: ['Any', 'Under 1M', 'Under 5M', 'Under 10M', 'Under 50M', 'Under 100M', 'Over 1M', 'Over 5M', 'Over 10M', 'Over 50M', 'Over 100M']
};

export const signals = [
  'None (all stocks)',
  'Top Gainers',
  'Top Losers',
  'New High',
  'New Low',
  'Most Volatile',
  'Most Active',
  'Unusual Volume',
  'Overbought',
  'Oversold',
  'Downgrades',
  'Upgrades',
  'Earnings Before',
  'Earnings After',
  'Recent Insider Buying',
  'Recent Insider Selling',
  'Major News',
  'Horizontal S/R',
  'TL Resistance',
  'TL Support',
  'Wedge Up',
  'Wedge Down',
  'Triangle Ascending',
  'Triangle Descending',
  'Channel Up',
  'Channel Down',
  'Double Top',
  'Double Bottom',
  'Multiple Top',
  'Multiple Bottom',
  'Head & Shoulders',
  'Head & Shoulders Inverse'
];

export const orderByOptions = [
  'Ticker',
  'Company',
  'Sector',
  'Industry',
  'Country',
  'Market Cap.',
  'P/E',
  'Price',
  'Change',
  'Volume'
];

